[package]
name = "neostake"
version = "1.0.0"
description = "hana neostake"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.7"
bincode = "1.3.3"
borsh = { version = "1.2.1", features = ["derive", "unstable__schema"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.1"
solana-program = "1.18.0"
thiserror = "1.0.52"

[dev-dependencies]
solana-program-test = "1.18.0"
solana-sdk = "1.18.0"
solana-vote-program = "1.18.0"
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]
